"""Argparse parser construction for matrix-ai-cli."""
from __future__ import annotations

import argparse
from typing import Any

from .config import (
    DEFAULT_BOUND,
    DEFAULT_MEDIA_BOUND,
    VIDEO_CHUNK_SIZE,
)
from .cli import (
    JsonArgumentParser,
    cmd_captcha_probe,
    cmd_captcha_ticket,
    cmd_check_text,
    cmd_check_image,
    cmd_detect_text,
    cmd_doctor,
    cmd_extract_pdf,
    cmd_feedback,
    cmd_pick_fp,
    cmd_render_pdf,
    cmd_run,
    cmd_run_pure,
    cmd_stress_pure,
    cmd_ticket,
)
from .cli_batch import cmd_check_images
from .cli_video import (
    cmd_check_video,
    cmd_stress_media,
)
from .cli_drain import cmd_check_images_drain


def build_parser() -> argparse.ArgumentParser:
    p = JsonArgumentParser(prog='matrix-ai-cli')
    sp = p.add_subparsers(dest='cmd', required=True)

    doctor = sp.add_parser('doctor')
    doctor.add_argument('--pure', action='store_true')
    doctor.set_defaults(func=cmd_doctor)

    pick = sp.add_parser('pick-fp')
    pick.add_argument('--max-tries', type=int, default=20)
    pick.add_argument('--fp-mode', choices=['fixed', 'fresh'], default='fixed')
    pick.add_argument('--xff', default='', help='spoof X-Forwarded-For for pure WS replay')
    pick.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    pick.set_defaults(func=cmd_pick_fp)

    detect = sp.add_parser('detect-text')
    detect.add_argument('--fp', default='')
    detect.add_argument('--fp-mode', choices=['fixed', 'fresh', 'pick'], default='fixed')
    detect.add_argument('--max-tries', type=int, default=20)
    detect.add_argument('--ticket')
    detect.add_argument('--randstr')
    detect.add_argument('--ticket-json')
    detect.add_argument('--ticket-command', default='', help='command that prints JSON with ticket/randstr for pure route')
    detect.add_argument('--auto-ticket', action=argparse.BooleanOptionalAction, default=True, help='run built-in ticket provider for pure route')
    detect.add_argument('--ticket-timeout', type=float, default=60.0)
    detect.add_argument('--ticket-attempts', type=int, default=2, help='built-in ticket provider attempts for text route')
    detect.add_argument('--ticket-provider-timeout', type=float, default=0.0, help='wall timeout for ticket provider command; 0 derives a bounded default')
    detect.add_argument('--ticket-provider-retries', type=int, default=1, help='provider command retries after timeout or bad output')
    detect.add_argument('--pure', action='store_true', help='disable browser/CDP ticket capture; require explicit fp and ticket/randstr')
    detect.add_argument('--driver', choices=['auto', 'pure', 'browser'], default='auto', help='agent route driver: auto tries pure, browser ticket flow, then pure without XFF')
    detect.add_argument('--route-order', default='', help='comma-separated text route order; default pure-auto,browser,pure-no-xff')
    detect.add_argument('--stop-on-first-failure', action='store_true', help='do not try fallback text routes')
    detect.add_argument('--browser-fp-mode', choices=['fixed', 'fresh', 'pick'], default='pick', help='fp mode used by browser fallback route')
    detect.add_argument('--order', choices=['ticket-text', 'fp-ticket-text', 'ticket-fp-text', 'fp-text-ticket', 'fp-ticket-text-immediate'], default='fp-ticket-text')
    detect.add_argument('--text-send-mode', choices=['on-code', 'evil0-only'], default='on-code')
    detect.add_argument('--bound', default=DEFAULT_BOUND)
    detect.add_argument('--session-id', default='')
    detect.add_argument('--capture-timeout', type=float, default=60.0)
    detect.add_argument('--text')
    detect.add_argument('--text-file')
    detect.add_argument('--timeout', type=float, default=20.0)
    detect.add_argument('--xff', default='', help='spoof X-Forwarded-For for pure WS replay')
    detect.add_argument('--rotate-xff', default='', help='derive XFF from pattern when route-mode is auto/on')
    detect.add_argument('--xff-pool', action='append', default=[], help='candidate XFF pool; first item is used for this single text run')
    detect.add_argument('--route-mode', choices=['auto', 'on', 'off'], default='auto', help='agent route policy for fresh pure text run')
    detect.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    detect.set_defaults(func=cmd_detect_text)

    render = sp.add_parser('render-pdf')
    render.add_argument('--report-json', required=True)
    render.add_argument('--text-file')
    render.add_argument('--out-pdf', required=True)
    render.set_defaults(func=cmd_render_pdf)

    extract = sp.add_parser('extract-pdf')
    extract.add_argument('--pdf', required=True)
    extract.set_defaults(func=cmd_extract_pdf)

    run = sp.add_parser('run')
    run.add_argument('--fp', default='')
    run.add_argument('--fp-mode', choices=['fixed', 'fresh', 'pick'], default='fresh')
    run.add_argument('--max-tries', type=int, default=20)
    run.add_argument('--ticket')
    run.add_argument('--randstr')
    run.add_argument('--ticket-json')
    run.add_argument('--ticket-command', default='', help='command that prints JSON with ticket/randstr for pure route')
    run.add_argument('--auto-ticket', action=argparse.BooleanOptionalAction, default=True, help='run built-in ticket provider for pure route')
    run.add_argument('--ticket-timeout', type=float, default=60.0)
    run.add_argument('--ticket-attempts', type=int, default=2, help='built-in ticket provider attempts for text route')
    run.add_argument('--ticket-provider-timeout', type=float, default=0.0, help='wall timeout for ticket provider command; 0 derives a bounded default')
    run.add_argument('--ticket-provider-retries', type=int, default=1, help='provider command retries after timeout or bad output')
    run.add_argument('--pure', action='store_true', help='disable browser/CDP ticket capture; require explicit fp and ticket/randstr')
    run.add_argument('--driver', choices=['auto', 'pure', 'browser'], default='auto', help='agent route driver: auto tries pure, browser ticket flow, then pure without XFF')
    run.add_argument('--route-order', default='', help='comma-separated text route order; default pure-auto,browser,pure-no-xff')
    run.add_argument('--stop-on-first-failure', action='store_true', help='do not try fallback text routes')
    run.add_argument('--browser-fp-mode', choices=['fixed', 'fresh', 'pick'], default='pick', help='fp mode used by browser fallback route')
    run.add_argument('--order', choices=['ticket-text', 'fp-ticket-text', 'ticket-fp-text', 'fp-text-ticket', 'fp-ticket-text-immediate'], default='fp-ticket-text')
    run.add_argument('--text-send-mode', choices=['on-code', 'evil0-only'], default='on-code')
    run.add_argument('--bound', default=DEFAULT_BOUND)
    run.add_argument('--session-id', default='')
    run.add_argument('--capture-timeout', type=float, default=60.0)
    run.add_argument('--text')
    run.add_argument('--text-file')
    run.add_argument('--timeout', type=float, default=20.0)
    run.add_argument('--xff', default='', help='spoof X-Forwarded-For for pure WS replay')
    run.add_argument('--rotate-xff', default='', help='derive XFF from pattern when route-mode is auto/on')
    run.add_argument('--xff-pool', action='append', default=[], help='candidate XFF pool; first item is used for this single text run')
    run.add_argument('--route-mode', choices=['auto', 'on', 'off'], default='auto', help='agent route policy for fresh pure text run')
    run.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    run.add_argument('--out-dir', default='', help='directory for report.json/PDF; omitted uses a temporary directory')
    run.add_argument('--no-pdf', action='store_true', help='write report.json only; do not render local PDF')
    run.set_defaults(func=cmd_run)

    ticket = sp.add_parser('ticket')
    ticket.add_argument('--mode', choices=['standalone', 'submit-hook', 'pure'], default='standalone')
    ticket.add_argument('--fp', default='')
    ticket.add_argument('--fp-mode', choices=['fixed', 'pick'], default='fixed')
    ticket.add_argument('--max-tries', type=int, default=20)
    ticket.add_argument('--bound', default=DEFAULT_BOUND)
    ticket.add_argument('--session-id', default='')
    ticket.add_argument('--timeout', type=float, default=30.0)
    ticket.add_argument('--text')
    ticket.add_argument('--text-file')
    ticket.add_argument('--out-json', default='')
    ticket.set_defaults(func=cmd_ticket)

    cap_ticket = sp.add_parser('captcha-ticket')
    cap_ticket.add_argument('--mode', choices=['validated', 'tdc', 'terror'], default='validated')
    cap_ticket.add_argument('--timeout', type=float, default=20.0)
    cap_ticket.add_argument('--attempts', type=int, default=20)
    cap_ticket.add_argument('--fp', default='')
    cap_ticket.add_argument('--xff', default='')
    cap_ticket.add_argument('--text')
    cap_ticket.add_argument('--text-file')
    cap_ticket.add_argument('--out-json', default='')
    cap_ticket.set_defaults(func=cmd_captcha_ticket)

    captcha = sp.add_parser('captcha-probe')
    captcha.add_argument('--timeout', type=float, default=20.0)
    captcha.add_argument('--out-json', default='')
    captcha.set_defaults(func=cmd_captcha_probe)

    feedback = sp.add_parser('feedback')
    feedback.add_argument('--fp', default='')
    feedback.add_argument('--report-json', required=True)
    feedback.add_argument('--status', action=argparse.BooleanOptionalAction, default=True)
    feedback.add_argument('--timeout', type=float, default=20.0)
    feedback.set_defaults(func=cmd_feedback)

    check_text = sp.add_parser('check-text')
    check_text.add_argument('--fp', default='')
    check_text.add_argument('--fp-mode', choices=['fixed', 'fresh'], default='fresh')
    check_text.add_argument('--ticket')
    check_text.add_argument('--randstr')
    check_text.add_argument('--ticket-json')
    check_text.add_argument('--driver', choices=['auto', 'pure', 'browser'], default='auto', help='agent route driver: auto tries pure, browser ticket flow, then pure without XFF')
    check_text.add_argument('--route-order', default='', help='comma-separated text route order; default pure-auto,browser,pure-no-xff')
    check_text.add_argument('--stop-on-first-failure', action='store_true', help='do not try fallback text routes')
    check_text.add_argument('--browser-fp-mode', choices=['fixed', 'fresh', 'pick'], default='pick', help='fp mode used by browser fallback route')
    check_text.add_argument('--max-tries', type=int, default=20)
    check_text.add_argument('--bound', default=DEFAULT_BOUND)
    check_text.add_argument('--session-id', default='')
    check_text.add_argument('--capture-timeout', type=float, default=60.0)
    check_text.add_argument('--ticket-command', default='', help='command that prints JSON with ticket/randstr')
    check_text.add_argument('--auto-ticket', action=argparse.BooleanOptionalAction, default=True, help='run built-in ticket provider before pure WS replay')
    check_text.add_argument('--ticket-timeout', type=float, default=60.0)
    check_text.add_argument('--ticket-attempts', type=int, default=2, help='built-in ticket provider attempts for text route')
    check_text.add_argument('--ticket-provider-timeout', type=float, default=0.0, help='wall timeout for ticket provider command; 0 derives a bounded default')
    check_text.add_argument('--ticket-provider-retries', type=int, default=1, help='provider command retries after timeout or bad output')
    check_text.add_argument('--text')
    check_text.add_argument('--text-file')
    check_text.add_argument('--timeout', type=float, default=20.0)
    check_text.add_argument('--text-send-mode', choices=['on-code', 'evil0-only'], default='on-code')
    check_text.add_argument('--order', choices=['ticket-text', 'fp-ticket-text', 'ticket-fp-text', 'fp-text-ticket', 'fp-ticket-text-immediate'], default='fp-ticket-text')
    check_text.add_argument('--xff', default='', help='spoof X-Forwarded-For for pure WS replay')
    check_text.add_argument('--rotate-xff', default='', help='derive XFF from pattern when route-mode is auto/on')
    check_text.add_argument('--xff-pool', action='append', default=[], help='candidate XFF pool; first item is used for this single text run')
    check_text.add_argument('--route-mode', choices=['auto', 'on', 'off'], default='auto', help='agent route policy for fresh pure text run')
    check_text.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    check_text.add_argument('--out-dir', default='', help='directory for raw report.json; omitted uses a temporary directory')
    check_text.add_argument('--out-json', default='', help='optional path for compact result JSON')
    check_text.set_defaults(func=cmd_check_text)

    check_image = sp.add_parser('check-image')
    check_image.add_argument('--fp', default='')
    check_image.add_argument('--fp-mode', choices=['fixed', 'fresh'], default='fresh')
    check_image.add_argument('--ticket')
    check_image.add_argument('--randstr')
    check_image.add_argument('--ticket-json')
    check_image.add_argument('--ticket-command', default='', help='command that prints unconsumed JSON with ticket/randstr')
    check_image.add_argument('--auto-ticket', action=argparse.BooleanOptionalAction, default=True, help='run built-in pure TencentCaptcha ticket provider')
    check_image.add_argument('--ticket-timeout', type=float, default=30.0)
    check_image.add_argument('--ticket-attempts', type=int, default=3)
    check_image.add_argument('--captcha-wait-profile', choices=['auto', 'steady', 'fast'], default='auto')
    check_image.add_argument('--captcha-wait-ms', default='', help='comma-separated TDC wait milliseconds')
    check_image.add_argument('--captcha-wait-jitter-ms', type=int, default=1200)
    check_image.add_argument('--captcha-backoff-sec', type=float, default=20.0)
    check_image.add_argument('--captcha-backoff-jitter-sec', type=float, default=8.0)
    check_image.add_argument('--attempts', type=int, default=6, help='fresh ticket+detect retries for transient media failures')
    check_image.add_argument('--retry-risk', action=argparse.BooleanOptionalAction, default=False, help='retry captcha evil_level responses inside the same item; default is stop-loss')
    check_image.add_argument('--media-send-mode', choices=['evil0-only', 'on-code'], default='evil0-only', help='pure media payload send policy after captcha code')
    check_image.add_argument('--image-file', required=True)
    check_image.add_argument('--timeout', type=float, default=60.0)
    check_image.add_argument('--xff', default='', help='spoof X-Forwarded-For for pure WS replay')
    check_image.add_argument('--egress-proxy', default='', help='HTTP/SOCKS proxy for captcha HTTP and media WS real outbound egress')
    check_image.add_argument('--egress-scope', choices=['detect', 'all'], default='detect', help='detect routes only media WS through egress proxy; all also routes captcha HTTP')
    check_image.add_argument('--captcha-xff-mode', choices=['none', 'match'], default='none', help='whether captcha HTTP requests also receive --xff')
    check_image.add_argument('--tdc-profile-mode', choices=['fixed', 'random'], default='fixed', help='vary browser-like TDC runtime dimensions per ticket')
    check_image.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    check_image.add_argument('--out-dir', default='', help='optional directory for raw image-report.json')
    check_image.add_argument('--out-json', default='', help='optional path for compact result JSON')
    check_image.add_argument('--solve-risk', action='store_true', help='opinionated browser CDP route: local WS proxy, fresh fp, routed XFF, disposable tab, risk stop-loss')
    check_image.add_argument('--driver', choices=['pure', 'cdp'], default='pure')
    check_image.add_argument('--cdp-ws-mode', choices=['proxy', 'direct'], default='proxy', help='CDP media WebSocket mode: proxy allows XFF, direct uses browser-native wss')
    check_image.add_argument('--cdp-fp-source', choices=['cli', 'browser'], default='cli', help='CDP fp source: cli writes fresh/fixed fp, browser reuses page-generated fp')
    check_image.add_argument('--cdp-target-mode', choices=['extension-tab', 'browser-context'], default='extension-tab', help='CDP page execution target: managed extension tab or isolated browser context')
    check_image.add_argument('--cdp-browser-ws-endpoint', default='', help='explicit browser-level CDP websocket endpoint for browser-context mode')
    check_image.add_argument('--cdp-browser-version-url', default='', help='explicit http://host:port/json/version URL for browser-context mode')
    check_image.add_argument('--cdp-browser-state-file', default='', help='optional bridge state json path used to resolve browser ws endpoint')
    check_image.add_argument('--cdp-context-proxy-server', default='', help='proxyServer for Target.createBrowserContext in browser-context mode')
    check_image.add_argument('--cdp-reset-browser-fp', action=argparse.BooleanOptionalAction, default=None, help='when using --cdp-fp-source browser, clear origin fp before reload; default true for --fp-mode fresh')
    check_image.add_argument('--cdp-new-tab', action=argparse.BooleanOptionalAction, default=True)
    check_image.add_argument('--cdp-close-tab', action=argparse.BooleanOptionalAction, default=True)
    check_image.add_argument('--cdp-tab-wait-sec', type=float, default=4.0)
    check_image.add_argument('--cdp-auto-env', action=argparse.BooleanOptionalAction, default=False, help='auto prepare a real matrix media page when using bound CDP browser route')
    check_image.add_argument('--cdp-env-timeout', type=float, default=90.0)
    check_image.add_argument('--cdp-force-new-bound', action=argparse.BooleanOptionalAction, default=False, help='force opening a fresh bound media tab before CDP run')
    check_image.add_argument('--cdp-reset-bound-fp', action=argparse.BooleanOptionalAction, default=False, help='clear media-page localStorage fp and reload before the CDP run')
    check_image.add_argument('--cdp-auto-refresh-fp', action=argparse.BooleanOptionalAction, default=False, help='refresh the bound browser fp automatically when remaining uses are at or below --cdp-refresh-threshold')
    check_image.add_argument('--cdp-refresh-threshold', type=int, default=1, help='remaining-use threshold for --cdp-auto-refresh-fp')
    check_image.add_argument('--cdp-auto-feedback', action=argparse.BooleanOptionalAction, default=False, help='after a successful CDP media result, submit positive browser-side feedback to refresh available uses when server accepts it')
    check_image.add_argument('--bound', default=DEFAULT_MEDIA_BOUND, help='bound agent-browser tab alias used when --no-cdp-new-tab')
    check_image.add_argument('--session-id', default='', help='explicit agent-browser tab id used when --no-cdp-new-tab')
    check_image.set_defaults(func=cmd_check_image)

    check_images = sp.add_parser('check-images')
    check_images.add_argument('--fp', default='')
    check_images.add_argument('--fp-mode', choices=['fixed', 'fresh'], default='fresh')
    check_images.add_argument('--ticket')
    check_images.add_argument('--randstr')
    check_images.add_argument('--ticket-json')
    check_images.add_argument('--ticket-command', default='', help='command that prints unconsumed JSON with ticket/randstr')
    check_images.add_argument('--auto-ticket', action=argparse.BooleanOptionalAction, default=True, help='run built-in pure TencentCaptcha ticket provider')
    check_images.add_argument('--ticket-timeout', type=float, default=30.0)
    check_images.add_argument('--ticket-attempts', type=int, default=3)
    check_images.add_argument('--captcha-wait-profile', choices=['auto', 'steady', 'fast'], default='auto')
    check_images.add_argument('--captcha-wait-ms', default='', help='comma-separated TDC wait milliseconds')
    check_images.add_argument('--captcha-wait-jitter-ms', type=int, default=1200)
    check_images.add_argument('--captcha-backoff-sec', type=float, default=20.0)
    check_images.add_argument('--captcha-backoff-jitter-sec', type=float, default=8.0)
    check_images.add_argument('--attempts', type=int, default=6, help='fresh ticket+detect retries for transient media failures')
    check_images.add_argument('--refresh-fp-on-retry', action=argparse.BooleanOptionalAction, default=False, help='use a fresh fp as well as a fresh ticket/route slot for each retry')
    check_images.add_argument('--retry-risk', action=argparse.BooleanOptionalAction, default=False, help='retry captcha evil_level responses inside the same item; default is stop-loss')
    check_images.add_argument('--media-send-mode', choices=['evil0-only', 'on-code'], default='evil0-only', help='pure media payload send policy after captcha code')
    check_images.add_argument('--image-file', action='append', default=[], help='image file; repeatable')
    check_images.add_argument('--image-dir', action='append', default=[], help='directory containing jpg/jpeg/png/webp images; repeatable')
    check_images.add_argument('--images-file', default='', help='newline-delimited image path manifest')
    check_images.add_argument('--allow-duplicate-images', action='store_true', help='preserve duplicate image paths from manifests; used by risk-guard resume queues')
    check_images.add_argument('--recursive', action='store_true', help='recurse image directories')
    check_images.add_argument('--repeat-each', type=int, default=1, help='repeat each discovered image N times for stress')
    check_images.add_argument('--timeout', type=float, default=60.0)
    check_images.add_argument('--xff', default='', help='spoof fixed X-Forwarded-For for pure WS replay')
    check_images.add_argument('--rotate-xff', default='', help='per-image XFF pattern; use 10.88.0.{i} or 10.88.0.')
    check_images.add_argument('--xff-pool', action='append', default=[], help='exact XFF address pool for queue rotation; repeatable or comma-separated')
    check_images.add_argument('--egress-proxy', default='', help='fixed HTTP/SOCKS proxy for captcha HTTP and media WS real outbound egress')
    check_images.add_argument('--egress-proxy-pool', action='append', default=[], help='HTTP/SOCKS proxy pool for per-image real outbound egress rotation; repeatable or comma-separated')
    check_images.add_argument('--egress-scope', choices=['detect', 'all'], default='detect', help='detect routes only media WS through egress proxy; all also routes captcha HTTP')
    check_images.add_argument('--preferred-xff-max-uses', type=int, default=-1, help='max consecutive successful uses of a preferred XFF before returning to pool rotation; -1 auto, 0 unlimited')
    check_images.add_argument('--route-mode', choices=['auto', 'on', 'off'], default='auto', help='agent route policy: auto builds a fresh XFF pool only when no fixed/rotate route is supplied; on requires --xff/--xff-pool/--rotate-xff or fresh auto pool')
    check_images.add_argument('--xff-probe', action=argparse.BooleanOptionalAction, default=False, help='probe rotate-xff candidates before batch run and auto-pick first passing candidate')
    check_images.add_argument('--xff-probe-pattern', action='append', default=[], help='candidate rotate-xff template for preflight probe; repeatable')
    check_images.add_argument('--xff-probe-attempts', type=int, default=1, help='attempts per xff probe candidate')
    check_images.add_argument('--xff-probe-max-patterns', type=int, default=0, help='limit number of xff probe candidates; 0 means all')
    check_images.add_argument('--concurrency', type=int, default=1, help='max concurrent image detections')
    check_images.add_argument('--ticket-phase', choices=['parallel', 'serial', 'prefetch', 'browser-pool'], default='parallel', help='serial/prefetch acquire tickets before media detect; browser-pool uses live browser ticket capture with auto-replenishment')
    check_images.add_argument('--captcha-xff-mode', choices=['none', 'match'], default='none', help='whether captcha HTTP requests also receive the per-item XFF')
    check_images.add_argument('--tdc-profile-mode', choices=['fixed', 'random'], default='fixed', help='vary browser-like TDC runtime dimensions per ticket')
    check_images.add_argument('--ticket-delay-sec', type=float, default=None, help='serial ticket phase delay before each item after first; defaults to --delay-sec')
    check_images.add_argument('--ticket-jitter-sec', type=float, default=None, help='serial ticket phase random extra delay; defaults to --jitter-sec')
    check_images.add_argument('--ticket-window-size', type=int, default=0, help='serial ticket phase detect window size; defaults to --concurrency')

    check_images.add_argument('--browser-pool-bound', default='', help='bound media tab alias used by --ticket-phase browser-pool')
    check_images.add_argument('--browser-pool-session-id', default='', help='explicit bound tab id used by --ticket-phase browser-pool')
    check_images.add_argument('--browser-pool-max-uses', type=int, default=1, help='pure browser-pool captures are single-use tickets; values above 1 are clamped to 1')
    check_images.add_argument('--browser-pool-cooldown', type=float, default=2.0, help='seconds between browser-pool replenishment attempts')
    check_images.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    check_images.add_argument('--out-dir', required=True, help='directory for summary.json, results.jsonl, and raw reports')
    check_images.add_argument('--out-json', default='', help='optional path for compact summary JSON')
    check_images.add_argument('--solve-risk', action='store_true', help='opinionated browser CDP route: local WS proxy, fresh fp, routed XFF pool, disposable tabs, risk stop-loss')
    check_images.add_argument('--driver', choices=['pure', 'cdp'], default='pure')
    check_images.add_argument('--cdp-ws-mode', choices=['proxy', 'direct'], default='proxy', help='CDP media WebSocket mode: proxy allows XFF, direct uses browser-native wss')
    check_images.add_argument('--cdp-fp-source', choices=['cli', 'browser'], default='cli', help='CDP fp source: cli writes fresh/fixed fp, browser reuses page-generated fp')
    check_images.add_argument('--cdp-target-mode', choices=['extension-tab', 'browser-context'], default='extension-tab', help='CDP page execution target: managed extension tab or isolated browser context')
    check_images.add_argument('--cdp-browser-ws-endpoint', default='', help='explicit browser-level CDP websocket endpoint for browser-context mode')
    check_images.add_argument('--cdp-browser-version-url', default='', help='explicit http://host:port/json/version URL for browser-context mode')
    check_images.add_argument('--cdp-browser-version-url-pool', action='append', default=[], help='candidate browser json/version URLs for CDP queue rotation; repeatable')
    check_images.add_argument('--cdp-browser-state-file', default='', help='optional bridge state json path used to resolve browser ws endpoint')
    check_images.add_argument('--cdp-context-proxy-server', default='', help='proxyServer for Target.createBrowserContext in browser-context mode')
    check_images.add_argument('--cdp-context-proxy-pool', action='append', default=[], help='browser-context proxyServer pool; repeatable or comma-separated')
    check_images.add_argument('--cdp-reset-browser-fp', action=argparse.BooleanOptionalAction, default=None, help='when using --cdp-fp-source browser, clear origin fp before reload; default true for --fp-mode fresh')
    check_images.add_argument('--cdp-new-tab', action=argparse.BooleanOptionalAction, default=True)
    check_images.add_argument('--cdp-close-tab', action=argparse.BooleanOptionalAction, default=True)
    check_images.add_argument('--cdp-tab-wait-sec', type=float, default=4.0)
    check_images.add_argument('--cdp-auto-env', action=argparse.BooleanOptionalAction, default=False, help='auto prepare real matrix media page(s) for bound CDP browser route')
    check_images.add_argument('--cdp-env-timeout', type=float, default=90.0)
    check_images.add_argument('--cdp-force-new-bound', action=argparse.BooleanOptionalAction, default=False, help='force opening fresh bound media tabs before the batch run')
    check_images.add_argument('--cdp-reset-bound-fp', action=argparse.BooleanOptionalAction, default=False, help='clear media-page localStorage fp and reload before the batch run')
    check_images.add_argument('--cdp-auto-refresh-fp', action=argparse.BooleanOptionalAction, default=False, help='refresh bound browser fp automatically when remaining uses are at or below --cdp-refresh-threshold')
    check_images.add_argument('--cdp-refresh-threshold', type=int, default=1, help='remaining-use threshold for --cdp-auto-refresh-fp')
    check_images.add_argument('--cdp-auto-feedback', action=argparse.BooleanOptionalAction, default=False, help='after each successful CDP media result, submit positive browser-side feedback to refresh available uses when server accepts it')
    check_images.add_argument('--cdp-bound-pool', action='append', default=[], help='bound tab alias pool for concurrent CDP browser queue; repeatable or comma-separated')
    check_images.add_argument('--cdp-browser-pool-size', type=int, default=0, help='auto-create N bound media tabs using --cdp-bound-prefix; 0 means one tab unless --solve-risk with concurrency>1')
    check_images.add_argument('--cdp-bound-prefix', default='', help='prefix for auto-created CDP media bound aliases; default uses --bound')
    check_images.add_argument('--bound', default=DEFAULT_MEDIA_BOUND, help='bound agent-browser tab alias used when --no-cdp-new-tab')
    check_images.add_argument('--session-id', default='', help='explicit agent-browser tab id used when --no-cdp-new-tab')
    check_images.add_argument('--delay-sec', type=float, default=2.0, help='sleep before each image after the first')
    check_images.add_argument('--jitter-sec', type=float, default=2.0, help='random extra sleep before each image after the first')
    check_images.add_argument('--risk-budget', type=int, default=0, help='captcha evil_level>0 events allowed before queue stop; default 0 stops before the next item')
    check_images.add_argument('--risk-cooldown-sec', type=float, default=300.0, help='cooldown seconds written to queue_health after risk stop; no implicit sleep')
    check_images.add_argument('--safe-queue', action='store_true', help='enable conservative CDP queue windows: cap each burst and sleep between windows')
    check_images.add_argument('--risk-window-size', type=int, default=0, help='max detections per burst before --risk-window-cooldown-sec; 0 disables unless --safe-queue')
    check_images.add_argument('--risk-window-cooldown-sec', type=float, default=None, help='sleep between risk windows; --safe-queue defaults to --risk-cooldown-sec')
    check_images.add_argument('--risk-recover', action=argparse.BooleanOptionalAction, default=False, help='keep the queue inside one command: on captcha risk, cool down and retry the same item with a fresh route slot')
    check_images.add_argument('--risk-recover-max-events', type=int, default=20, help='maximum captcha-risk recovery events before final stop')
    check_images.add_argument('--risk-recover-cooldown-sec', type=float, default=None, help='cooldown seconds for --risk-recover; defaults to --risk-cooldown-sec')
    check_images.add_argument('--no-risk-guard', action='store_true', help='disable default risk serialization/stop guard')
    check_images.add_argument('--stop-on-fail', action='store_true')
    check_images.set_defaults(func=cmd_check_images)

    check_images_drain = sp.add_parser('check-images-drain')
    check_images_drain.add_argument('--fp', default='')
    check_images_drain.add_argument('--fp-mode', choices=['fixed', 'fresh'], default='fresh')
    check_images_drain.add_argument('--ticket', default=None)
    check_images_drain.add_argument('--randstr', default=None)
    check_images_drain.add_argument('--ticket-json', default=None)
    check_images_drain.add_argument('--ticket-command', default='', help='command that prints unconsumed JSON with ticket/randstr')
    check_images_drain.add_argument('--auto-ticket', action=argparse.BooleanOptionalAction, default=True)
    check_images_drain.add_argument('--ticket-timeout', type=float, default=60.0)
    check_images_drain.add_argument('--ticket-attempts', type=int, default=2)
    check_images_drain.add_argument('--captcha-wait-profile', choices=['auto', 'steady', 'fast'], default='auto')
    check_images_drain.add_argument('--captcha-wait-ms', default='500')
    check_images_drain.add_argument('--captcha-wait-jitter-ms', type=int, default=0)
    check_images_drain.add_argument('--captcha-backoff-sec', type=float, default=20.0)
    check_images_drain.add_argument('--captcha-backoff-jitter-sec', type=float, default=8.0)
    check_images_drain.add_argument('--attempts', type=int, default=1)
    check_images_drain.add_argument('--refresh-fp-on-retry', action=argparse.BooleanOptionalAction, default=False)
    check_images_drain.add_argument('--retry-risk', action=argparse.BooleanOptionalAction, default=False)
    check_images_drain.add_argument('--media-send-mode', choices=['evil0-only', 'on-code'], default='on-code')
    check_images_drain.add_argument('--image-file', action='append', default=[])
    check_images_drain.add_argument('--image-dir', action='append', default=[])
    check_images_drain.add_argument('--images-file', default='')
    check_images_drain.add_argument('--allow-duplicate-images', action='store_true')
    check_images_drain.add_argument('--recursive', action='store_true')
    check_images_drain.add_argument('--repeat-each', type=int, default=1)
    check_images_drain.add_argument('--timeout', type=float, default=70.0)
    check_images_drain.add_argument('--xff', default='')
    check_images_drain.add_argument('--rotate-xff', default='')
    check_images_drain.add_argument('--xff-pool', action='append', default=[])
    check_images_drain.add_argument('--egress-proxy', default='')
    check_images_drain.add_argument('--egress-proxy-pool', action='append', default=[])
    check_images_drain.add_argument('--egress-scope', choices=['detect', 'all'], default='detect')
    check_images_drain.add_argument('--preferred-xff-max-uses', type=int, default=-1)
    check_images_drain.add_argument('--route-mode', choices=['auto', 'on', 'off'], default='auto')
    check_images_drain.add_argument('--xff-probe', action=argparse.BooleanOptionalAction, default=False)
    check_images_drain.add_argument('--xff-probe-pattern', action='append', default=[])
    check_images_drain.add_argument('--xff-probe-attempts', type=int, default=1)
    check_images_drain.add_argument('--xff-probe-max-patterns', type=int, default=0)
    check_images_drain.add_argument('--concurrency', type=int, default=5)
    check_images_drain.add_argument('--ticket-phase', choices=['parallel', 'serial', 'prefetch', 'browser-pool'], default='serial')
    check_images_drain.add_argument('--captcha-xff-mode', choices=['none', 'match'], default='none')
    check_images_drain.add_argument('--tdc-profile-mode', choices=['fixed', 'random'], default='fixed')
    check_images_drain.add_argument('--ticket-delay-sec', type=float, default=1.5)
    check_images_drain.add_argument('--ticket-jitter-sec', type=float, default=0.0)
    check_images_drain.add_argument('--ticket-window-size', type=int, default=5)

    check_images_drain.add_argument('--browser-pool-bound', default='', help='bound media tab alias used by --ticket-phase browser-pool')
    check_images_drain.add_argument('--browser-pool-session-id', default='', help='explicit bound tab id used by --ticket-phase browser-pool')
    check_images_drain.add_argument('--browser-pool-max-uses', type=int, default=1, help='pure browser-pool captures are single-use tickets; values above 1 are clamped to 1')
    check_images_drain.add_argument('--browser-pool-cooldown', type=float, default=2.0, help='seconds between browser-pool replenishment attempts')
    check_images_drain.add_argument('--header', action='append', default=[])
    check_images_drain.add_argument('--out-dir', required=True)
    check_images_drain.add_argument('--out-json', default='')
    check_images_drain.add_argument('--solve-risk', action='store_true')
    check_images_drain.add_argument('--driver', choices=['pure', 'cdp'], default='pure')
    check_images_drain.add_argument('--cdp-ws-mode', choices=['proxy', 'direct'], default='proxy', help='CDP media WebSocket mode: proxy allows XFF, direct uses browser-native wss')
    check_images_drain.add_argument('--cdp-fp-source', choices=['cli', 'browser'], default='cli', help='CDP fp source: cli writes fresh/fixed fp, browser reuses page-generated fp')
    check_images_drain.add_argument('--cdp-target-mode', choices=['extension-tab', 'browser-context'], default='extension-tab', help='CDP page execution target: managed extension tab or isolated browser context')
    check_images_drain.add_argument('--cdp-browser-ws-endpoint', default='', help='explicit browser-level CDP websocket endpoint for browser-context mode')
    check_images_drain.add_argument('--cdp-browser-version-url', default='', help='explicit http://host:port/json/version URL for browser-context mode')
    check_images_drain.add_argument('--cdp-browser-version-url-pool', action='append', default=[], help='candidate browser json/version URLs for CDP queue rotation; repeatable')
    check_images_drain.add_argument('--cdp-browser-state-file', default='', help='optional bridge state json path used to resolve browser ws endpoint')
    check_images_drain.add_argument('--cdp-context-proxy-server', default='', help='proxyServer for Target.createBrowserContext in browser-context mode')
    check_images_drain.add_argument('--cdp-context-proxy-pool', action='append', default=[], help='browser-context proxyServer pool; repeatable or comma-separated')
    check_images_drain.add_argument('--cdp-reset-browser-fp', action=argparse.BooleanOptionalAction, default=None, help='when using --cdp-fp-source browser, clear origin fp before reload; default true for --fp-mode fresh')
    check_images_drain.add_argument('--cdp-new-tab', action=argparse.BooleanOptionalAction, default=True)
    check_images_drain.add_argument('--cdp-close-tab', action=argparse.BooleanOptionalAction, default=True)
    check_images_drain.add_argument('--cdp-tab-wait-sec', type=float, default=4.0)
    check_images_drain.add_argument('--cdp-auto-env', action=argparse.BooleanOptionalAction, default=False, help='auto prepare real matrix media page(s) for bound CDP browser route')
    check_images_drain.add_argument('--cdp-env-timeout', type=float, default=90.0)
    check_images_drain.add_argument('--cdp-force-new-bound', action=argparse.BooleanOptionalAction, default=False, help='force opening fresh bound media tabs before the batch run')
    check_images_drain.add_argument('--cdp-reset-bound-fp', action=argparse.BooleanOptionalAction, default=False, help='clear media-page localStorage fp and reload before the batch run')
    check_images_drain.add_argument('--cdp-auto-refresh-fp', action=argparse.BooleanOptionalAction, default=False, help='refresh bound browser fp automatically when remaining uses are at or below --cdp-refresh-threshold')
    check_images_drain.add_argument('--cdp-refresh-threshold', type=int, default=1, help='remaining-use threshold for --cdp-auto-refresh-fp')
    check_images_drain.add_argument('--cdp-auto-feedback', action=argparse.BooleanOptionalAction, default=False, help='after each successful CDP media result, submit positive browser-side feedback to refresh available uses when server accepts it')
    check_images_drain.add_argument('--cdp-bound-pool', action='append', default=[], help='bound tab alias pool for concurrent CDP browser queue; repeatable or comma-separated')
    check_images_drain.add_argument('--cdp-browser-pool-size', type=int, default=0, help='auto-create N bound media tabs using --cdp-bound-prefix; 0 means one tab unless --solve-risk with concurrency>1')
    check_images_drain.add_argument('--cdp-bound-prefix', default='', help='prefix for auto-created CDP media bound aliases; default uses --bound')
    check_images_drain.add_argument('--bound', default=DEFAULT_MEDIA_BOUND, help='bound agent-browser tab alias used when --no-cdp-new-tab')
    check_images_drain.add_argument('--session-id', default='', help='explicit agent-browser tab id used when --no-cdp-new-tab')
    check_images_drain.add_argument('--delay-sec', type=float, default=0.0)
    check_images_drain.add_argument('--jitter-sec', type=float, default=0.0)
    check_images_drain.add_argument('--risk-budget', type=int, default=0)
    check_images_drain.add_argument('--risk-cooldown-sec', type=float, default=0.0)
    check_images_drain.add_argument('--safe-queue', action='store_true')
    check_images_drain.add_argument('--risk-window-size', type=int, default=0)
    check_images_drain.add_argument('--risk-window-cooldown-sec', type=float, default=None)
    check_images_drain.add_argument('--risk-recover', action=argparse.BooleanOptionalAction, default=False)
    check_images_drain.add_argument('--risk-recover-max-events', type=int, default=0)
    check_images_drain.add_argument('--risk-recover-cooldown-sec', type=float, default=None)
    check_images_drain.add_argument('--no-risk-guard', action='store_true')
    check_images_drain.add_argument('--stop-on-fail', action='store_true')
    check_images_drain.add_argument('--drain-window-size', type=int, default=5, help='number of pending inputs attempted per internal queue window')
    check_images_drain.add_argument('--drain-max-windows', type=int, default=200, help='maximum internal windows before returning resumable summary')
    check_images_drain.add_argument('--drain-cooldown-sec', type=float, default=0.0, help='sleep between internal windows')
    check_images_drain.add_argument('--drain-target-success', type=int, default=0, help='target successful items; default all requested inputs')
    check_images_drain.add_argument('--drain-reset', action='store_true', help='ignore existing completed-indices.txt in out-dir')
    check_images_drain.set_defaults(func=cmd_check_images_drain)

    check_video = sp.add_parser('check-video')
    check_video.add_argument('--fp', default='')
    check_video.add_argument('--fp-mode', choices=['fixed', 'fresh'], default='fresh')
    check_video.add_argument('--ticket')
    check_video.add_argument('--randstr')
    check_video.add_argument('--ticket-json')
    check_video.add_argument('--ticket-command', default='', help='command that prints unconsumed JSON with ticket/randstr')
    check_video.add_argument('--auto-ticket', action=argparse.BooleanOptionalAction, default=True, help='run built-in pure TencentCaptcha ticket provider')
    check_video.add_argument('--ticket-timeout', type=float, default=30.0)
    check_video.add_argument('--ticket-attempts', type=int, default=3)
    check_video.add_argument('--captcha-wait-profile', choices=['auto', 'steady', 'fast'], default='auto')
    check_video.add_argument('--captcha-wait-ms', default='', help='comma-separated TDC wait milliseconds')
    check_video.add_argument('--captcha-wait-jitter-ms', type=int, default=1200)
    check_video.add_argument('--captcha-backoff-sec', type=float, default=20.0)
    check_video.add_argument('--captcha-backoff-jitter-sec', type=float, default=8.0)
    check_video.add_argument('--attempts', type=int, default=6, help='fresh ticket+detect retries for transient media failures')
    check_video.add_argument('--retry-risk', action=argparse.BooleanOptionalAction, default=False, help='retry captcha evil_level responses inside the same item; default is stop-loss')
    check_video.add_argument('--media-send-mode', choices=['evil0-only', 'on-code'], default='evil0-only', help='pure media payload send policy after captcha code')
    check_video.add_argument('--video-file', required=True)
    check_video.add_argument('--timeout', type=float, default=90.0)
    check_video.add_argument('--upload-timeout', type=float, default=90.0)
    check_video.add_argument('--chunk-size', type=int, default=VIDEO_CHUNK_SIZE)
    check_video.add_argument('--xff', default='', help='spoof X-Forwarded-For for pure WS replay and upload')
    check_video.add_argument('--egress-proxy', default='', help='HTTP/SOCKS proxy for video upload, captcha HTTP, and media WS real outbound egress')
    check_video.add_argument('--egress-scope', choices=['detect', 'all'], default='detect', help='detect routes only media WS through egress proxy; all also routes captcha HTTP')
    check_video.add_argument('--captcha-xff-mode', choices=['none', 'match'], default='none', help='whether captcha HTTP requests also receive --xff')
    check_video.add_argument('--tdc-profile-mode', choices=['fixed', 'random'], default='fixed', help='vary browser-like TDC runtime dimensions per ticket')
    check_video.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    check_video.add_argument('--out-dir', default='', help='optional directory for raw video-report.json')
    check_video.add_argument('--out-json', default='', help='optional path for compact result JSON')
    check_video.add_argument('--solve-risk', action='store_true', help='opinionated browser CDP route: local WS proxy, fresh fp, routed XFF, disposable tab, risk stop-loss')
    check_video.add_argument('--driver', choices=['pure', 'cdp'], default='pure')
    check_video.add_argument('--cdp-ws-mode', choices=['proxy', 'direct'], default='proxy', help='CDP media WebSocket mode: proxy allows XFF, direct uses browser-native wss')
    check_video.add_argument('--cdp-fp-source', choices=['cli', 'browser'], default='cli', help='CDP fp source: cli writes fresh/fixed fp, browser reuses page-generated fp')
    check_video.add_argument('--cdp-target-mode', choices=['extension-tab', 'browser-context'], default='extension-tab', help='CDP page execution target: managed extension tab or isolated browser context')
    check_video.add_argument('--cdp-browser-ws-endpoint', default='', help='explicit browser-level CDP websocket endpoint for browser-context mode')
    check_video.add_argument('--cdp-browser-version-url', default='', help='explicit http://host:port/json/version URL for browser-context mode')
    check_video.add_argument('--cdp-browser-state-file', default='', help='optional bridge state json path used to resolve browser ws endpoint')
    check_video.add_argument('--cdp-context-proxy-server', default='', help='proxyServer for Target.createBrowserContext in browser-context mode')
    check_video.add_argument('--cdp-reset-browser-fp', action=argparse.BooleanOptionalAction, default=None, help='when using --cdp-fp-source browser, clear origin fp before reload; default true for --fp-mode fresh')
    check_video.add_argument('--cdp-new-tab', action=argparse.BooleanOptionalAction, default=True)
    check_video.add_argument('--cdp-close-tab', action=argparse.BooleanOptionalAction, default=True)
    check_video.add_argument('--cdp-tab-wait-sec', type=float, default=4.0)
    check_video.add_argument('--cdp-auto-env', action=argparse.BooleanOptionalAction, default=False, help='auto prepare a real matrix media page when using bound CDP browser route')
    check_video.add_argument('--cdp-env-timeout', type=float, default=90.0)
    check_video.add_argument('--cdp-force-new-bound', action=argparse.BooleanOptionalAction, default=False, help='force opening a fresh bound media tab before CDP run')
    check_video.add_argument('--cdp-reset-bound-fp', action=argparse.BooleanOptionalAction, default=False, help='clear media-page localStorage fp and reload before the CDP run')
    check_video.add_argument('--cdp-auto-refresh-fp', action=argparse.BooleanOptionalAction, default=False, help='refresh the bound browser fp automatically when remaining uses are at or below --cdp-refresh-threshold')
    check_video.add_argument('--cdp-refresh-threshold', type=int, default=1, help='remaining-use threshold for --cdp-auto-refresh-fp')
    check_video.add_argument('--cdp-auto-feedback', action=argparse.BooleanOptionalAction, default=False, help='after a successful CDP media result, submit positive browser-side feedback to refresh available uses when server accepts it')
    check_video.add_argument('--bound', default=DEFAULT_MEDIA_BOUND, help='bound agent-browser tab alias used when --no-cdp-new-tab')
    check_video.add_argument('--session-id', default='', help='explicit agent-browser tab id used when --no-cdp-new-tab')
    check_video.set_defaults(func=cmd_check_video)

    stress_media = sp.add_parser('stress-media')
    stress_media.add_argument('--count', type=int, default=100)
    stress_media.add_argument('--fp', default='')
    stress_media.add_argument('--fp-mode', choices=['fixed', 'fresh'], default='fresh')
    stress_media.add_argument('--timeout', type=float, default=15.0)
    stress_media.add_argument('--xff', default='', help='fixed X-Forwarded-For for media WS quota probe')
    stress_media.add_argument('--rotate-xff', default='', help='per-iteration XFF pattern; default is a private 10.214.<bucket>.{i} pattern in fresh mode')
    stress_media.add_argument('--egress-proxy', default='', help='fixed HTTP/SOCKS proxy for media WS real outbound egress')
    stress_media.add_argument('--egress-proxy-pool', action='append', default=[], help='HTTP/SOCKS proxy pool for per-iteration real outbound egress rotation; repeatable or comma-separated')
    stress_media.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    stress_media.add_argument('--out-dir', required=True, help='directory for stress-media-summary.json and attempts')
    stress_media.add_argument('--delay-sec', type=float, default=0.0)
    stress_media.add_argument('--jitter-sec', type=float, default=0.0)
    stress_media.add_argument('--stop-on-fail', action='store_true')
    stress_media.set_defaults(func=cmd_stress_media)

    run_pure = sp.add_parser('run-pure')
    run_pure.add_argument('--fp', default='')
    run_pure.add_argument('--fp-mode', choices=['fixed', 'fresh'], default='fresh', help='fixed keeps caller-managed fp/XFF; fresh enables auto XFF route unless --route-mode off')
    run_pure.add_argument('--ticket')
    run_pure.add_argument('--randstr')
    run_pure.add_argument('--ticket-json')
    run_pure.add_argument('--ticket-command', default='', help='command that prints JSON with ticket/randstr')
    run_pure.add_argument('--auto-ticket', action=argparse.BooleanOptionalAction, default=True, help='run built-in ticket provider before pure WS replay')
    run_pure.add_argument('--ticket-timeout', type=float, default=60.0)
    run_pure.add_argument('--ticket-attempts', type=int, default=2, help='built-in ticket provider attempts for text route')
    run_pure.add_argument('--ticket-provider-timeout', type=float, default=0.0, help='wall timeout for ticket provider command; 0 derives a bounded default')
    run_pure.add_argument('--ticket-provider-retries', type=int, default=1, help='provider command retries after timeout or bad output')
    run_pure.add_argument('--text')
    run_pure.add_argument('--text-file')
    run_pure.add_argument('--timeout', type=float, default=20.0)
    run_pure.add_argument('--text-send-mode', choices=['on-code', 'evil0-only'], default='on-code')
    run_pure.add_argument('--order', choices=['ticket-text', 'fp-ticket-text', 'ticket-fp-text', 'fp-text-ticket', 'fp-ticket-text-immediate'], default='fp-ticket-text')
    run_pure.add_argument('--xff', default='', help='spoof X-Forwarded-For for pure WS replay')
    run_pure.add_argument('--rotate-xff', default='', help='derive XFF from pattern when route-mode is auto/on')
    run_pure.add_argument('--xff-pool', action='append', default=[], help='candidate XFF pool; first item is used for this single text run')
    run_pure.add_argument('--route-mode', choices=['auto', 'on', 'off'], default='auto', help='agent route policy: auto derives XFF only for --fp-mode fresh; on requires --xff/--xff-pool/--rotate-xff or fresh mode')
    run_pure.add_argument('--route-order', default='', help='comma-separated pure text route order; default pure-auto,pure-no-xff')
    run_pure.add_argument('--stop-on-first-failure', action='store_true', help='do not try fallback pure text routes')
    run_pure.set_defaults(driver='pure')
    run_pure.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    run_pure.add_argument('--out-dir', default='', help='directory for report.json/PDF; omitted uses a temporary directory')
    run_pure.add_argument('--no-pdf', action='store_true', help='write report.json only; do not render local PDF')
    run_pure.add_argument('--result-only', action='store_true', help='stdout compact text check result instead of full detect report')
    run_pure.set_defaults(func=cmd_run_pure)

    stress = sp.add_parser('stress-pure')
    stress.add_argument('--fp', default='')
    stress.add_argument('--fp-mode', choices=['fixed', 'fresh'], default='fixed')
    stress.add_argument('--count', type=int, default=100)
    stress.add_argument('--ticket-command', default='', help='command that prints JSON with ticket/randstr for each iteration')
    stress.add_argument('--auto-ticket', action='store_true', help='run built-in ticket provider for each full-detect iteration')
    stress.add_argument('--ticket-timeout', type=float, default=60.0)
    stress.add_argument('--ticket-json', default='', help='static ticket JSON for deterministic one-time/reuse stress')
    stress.add_argument('--captcha-probe', action='store_true', help='stress TencentCaptcha pure prehandle/verify probe instead of Matrix fp handshake')
    stress.add_argument('--text')
    stress.add_argument('--text-file')
    stress.add_argument('--timeout', type=float, default=20.0)
    stress.add_argument('--text-send-mode', choices=['on-code', 'evil0-only'], default='on-code')
    stress.add_argument('--order', choices=['ticket-text', 'fp-ticket-text', 'ticket-fp-text', 'fp-text-ticket', 'fp-ticket-text-immediate'], default='fp-ticket-text')
    stress.add_argument('--xff', default='', help='spoof X-Forwarded-For for pure WS replay')
    stress.add_argument('--rotate-xff', default='', help='per-iteration XFF pattern; use 127.0.0. or 127.0.0.{i}')
    stress.add_argument('--header', action='append', default=[], help='extra WS header, e.g. Name: Value')
    stress.add_argument('--out-dir', required=True)
    stress.add_argument('--stop-on-fail', action='store_true')
    stress.set_defaults(func=cmd_stress_pure)

    return p
